-- Cria o banco
CREATE DATABASE IF NOT EXISTS CURSOSQL01;

USE CURSOSQL01;

-- Estrutura das tabelas
CREATE TABLE IF NOT EXISTS CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(70) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE IF NOT EXISTS TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL'),
	NUMERO VARCHAR(15),
	IDCLIENTE INT,
	FOREIGN KEY(IDCLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE IF NOT EXISTS ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	IDCLIENTE INT,
	FOREIGN KEY(IDCLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

ALTER TABLE ENDERECO ADD CIDADE VARCHAR(50) NOT NULL AFTER BAIRRO;

-- Cliente 
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','98547-6');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@TERA.COM','86664-7');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GLOBO.COM','75658-5');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','88657-5');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F', NULL,'99754-7');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','CELIA@TERRA.COM','77558-5');
INSERT INTO CLIENTE VALUES(NULL,'PEDRO','M','PEDRO@EMAIL.COM','75811-5');
INSERT INTO CLIENTE VALUES(NULL,'HENRIQUE','F','HENRIQUE@UOL.COM','73258-5');


SELECT * FROM CLIENTE C;

-- Telefone
INSERT INTO TELEFONE VALUES(NULL,'CEL','9955331',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','6574565',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','8864566',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','5557798',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','6765768',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','5676765',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','5765547',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','8865645',7);
INSERT INTO TELEFONE VALUES(NULL,'RES','7555446',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','5788654',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','7865644',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','5754644',6);

SELECT * FROM TELEFONE T;

-- Endereço 

INSERT INTO ENDERECO VALUES(NULL,'RUA A','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA C','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','ESTACIO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','B. HORIZONTE','MG',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','FLAMENGO','RIO DE JANEIRO','RJ',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','B. HORIZONTE','MG',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','CENTRO','NITERÓI','RJ',6);

SELECT * FROM ENDERECO E;