CREATE DATABASE IF NOT EXISTS PROJETO;
USE PROJETO;

CREATE TABLE IF NOT EXISTS CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	DOCUMENTO_FEDERAL VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CONTATO(
	ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('TEL','CEL','EMAIL') NOT NULL,
	CONTATO VARCHAR(70) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS MARCA(
	ID_MARCA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CARRO(
	ID_CARRO INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO_CHASSI VARCHAR(50) NOT NULL,
	ID_MARCA INT UNIQUE,
	FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA)
);

ALTER TABLE CARRO ADD ID_CLIENTE INT UNIQUE;
ALTER TABLE CARRO ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
DESCRIBE CARRO;

CREATE TABLE IF NOT EXISTS COR(
	ID_COR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(40) NOT NULL,
	ID_CARRO INT,
	FOREIGN KEY (ID_CARRO) REFERENCES CARRO(ID_CARRO)
);

SHOW TABLES;

-- Cadastro de dados
INSERT INTO CLIENTE VALUES (NULL, "ANDERSON", "12345678901");
SELECT * FROM CLIENTE C ;

INSERT INTO CONTATO VALUES (NULL, "EMAIL", "ANDERSON@EMAIL.COM", 1);
SELECT * FROM CONTATO;

INSERT INTO MARCA VALUES (NULL, 'HOT WHEELS');
SELECT * FROM MARCA;

INSERT INTO CARRO VALUES (NULL, '15644X143A8', 1, 1);
SELECT * FROM CARRO;

INSERT INTO COR VALUES (NULL, "PRETO", 1);
SELECT * FROM COR;

